language: node_js
node_js:
  - stable
  # until sinon release 2.0.0 stable, sinon-chai will have a broken dependency
  # npm 2 will error out in this case, so our legacy builds will fail
  # - '4'
notifications:
  email: false
  # webhooks:
  #   urls:
  #     - https://webhooks.gitter.im/e/...
  #   on_success: change  # options: [always|never|change] default: always
  #   on_failure: always  # options: [always|never|change] default: always
  #   on_start: never     # options: [always|never|change] default: always
script:
  - npm test
after_success:
deploy:
  provider: npm
  email: patricksissons@gmail.com
  on:
    tags: true
  api_key:
    secure: "lnSPPzTXpi7eNqlegKVB5aj2KzwQpFDjwU30D0cROtmg59uwTrcbaWTct/7Tz5iSTH84jzQQ5MLqcOHWE9iWCfHPZdIffVGr0cLIgX5cpQsuschO51/gMmZA2TQvJMQMnAAXOTdHIYSzrIohAnKPQmLMW5DaTOZzbe84rLk9VyeEWVCNcgE26KschI//3KSG1pExH7UnanUQdiO9LWKjufphskHUo6Qk3X/f/l8heC+P1SoUbxxRpbCK6OHIHb5MHmOoffST0u5gtFqk1p+gt9f9h0r0gt5Qln4AMLZ52KCHY9hnhI7rFsTe7E+O/ecgnnR0vbUTWwGTCeoiQFIda6CMWTmszY/aZOjMPfbqta9BPlKPb92i9HZO+UzNP4QBbrONczx3Qa2+bt47OM2RqSAqXuEifo+9Zzk4Xxq+UVCzknyER81SPTvXdjENZt6IEk0wWqGLa7faS9vGIQry0djIQ/G3wP33OSeZlESA7gRTklUbOp7JPcFX8qlSXKp/RMCixGYuU+VoScxHEa7Lks9ip1u1M7Wpd7T6XFYxYDIPGQvhS7yCkX3AIH1vQy1vjbBAyaLxtVIj1VMwNxVR5lL7BSbSEtUIdJr2xotwTzQ6cVK9OCwfdMV+KYN5vxMXT3Nm8wG2vaJaK02IvQNGkd1u6oEKL8iDw55gWaVSt60="
